# Generated by Django 5.2.12 on 2026-04-01 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigIntegerField(unique=True, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('cover_url', models.CharField(max_length=255, verbose_name='URL обложки')),
                ('url', models.CharField(max_length=500, verbose_name='URL книги')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('art_type', models.IntegerField(verbose_name='Тип контента')),
                ('prices', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_auto_speech_gift', models.BooleanField(default=False, verbose_name='Авто-озвучка в подарок')),
                ('min_age', models.PositiveIntegerField(verbose_name='Возрастные ограничения')),
                ('language_code', models.CharField(max_length=10, verbose_name='Код языка')),
                ('last_updated_at', models.DateTimeField(verbose_name='Дата последнего обновления')),
                ('last_released_at', models.DateTimeField(verbose_name='Дата последнего релиза')),
                ('availability', models.BooleanField(default=False, verbose_name='Доступность')),
                ('available_from', models.DateTimeField(verbose_name='Доступна с')),
                ('html_annotation', models.TextField(verbose_name='HTML-аннотация')),
                ('html_annotation_litres', models.TextField(verbose_name='HTML-аннотация Litres')),
                ('livelib_rated_count', models.IntegerField(verbose_name='Кол-во оценок LiveLib')),
                ('livelib_rated_avg', models.FloatField(verbose_name='Средняя оценка LiveLib')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
                ('contents_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL содержания')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigIntegerField(default=0, unique=True, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('full_rodit', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Copyrighter',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='ID копирайтера')),
                ('name', models.CharField(max_length=255, verbose_name='Название копирайтера')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Копирайтер',
                'verbose_name_plural': 'Копирайтеры',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID жанра')),
                ('uuid', models.UUIDField(verbose_name='UUID жанра')),
                ('name', models.CharField(max_length=255, verbose_name='Название жанров')),
                ('is_root', models.BooleanField(default=False, verbose_name='Корневой ли?')),
                ('url', models.CharField(max_length=255, verbose_name='URL жанра')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной ли?')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID издательства')),
                ('name', models.CharField(max_length=255, verbose_name='Название издательства')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL издательства')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.FloatField(blank=True, null=True, verbose_name='Рейтинг книги')),
                ('rated_1_count', models.IntegerField(default=0, verbose_name="Кол-во оценок '1'")),
                ('rated_2_count', models.IntegerField(default=0, verbose_name="Кол-во оценок '2'")),
                ('rated_3_count', models.IntegerField(default=0, verbose_name="Кол-во оценок '3'")),
                ('rated_4_count', models.IntegerField(default=0, verbose_name="Кол-во оценок '4'")),
                ('rated_5_count', models.IntegerField(default=0, verbose_name="Кол-во оценок '5'")),
                ('rated_avg', models.FloatField(verbose_name='Средний рейтинг')),
                ('rated_total_count', models.IntegerField(verbose_name='Общее кол-во оценок')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Rightholder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID правообладателя')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Правообладатель',
                'verbose_name_plural': 'Правообладатели',
            },
        ),
        migrations.CreateModel(
            name='BookContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', 'Author'), ('editor', 'Editor'), ('corrector', 'Corrector'), ('illustrator', 'Illustrator'), ('translator', 'Translator'), ('publisher', 'Publisher'), ('reader', 'Reader')], max_length=100, verbose_name='Вклад в книгу')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.contributor')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='contributors',
            field=models.ManyToManyField(related_name='books', through='bookshelf.BookContributor', to='bookshelf.contributor'),
        ),
        migrations.AddField(
            model_name='book',
            name='copyrighter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookshelf.copyrighter', verbose_name='Копирайтер'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='bookshelf.genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookshelf.publisher', verbose_name='Издатель'),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookshelf.rating', verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='book',
            name='rightholder',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='bookshelf.rightholder', verbose_name='Правообладатель'),
        ),
        migrations.AddConstraint(
            model_name='bookcontributor',
            constraint=models.UniqueConstraint(fields=('book', 'contributor', 'role'), name='unique_book_contributor_role'),
        ),
    ]
