# Generated by Django 5.2.12 on 2026-04-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_genre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
