# Generated by Django 5.2.12 on 2026-04-07 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_remove_genre_slug_book_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookshelf.book')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
            bases=('bookshelf.book',),
        ),
    ]
