# Generated by Django 5.2.12 on 2026-04-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bookshelf.book',),
        ),
    ]
