# Generated by Django 5.2.12 on 2026-04-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0005_delete_product_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Бестселлер ли?'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_sales_hit',
            field=models.BooleanField(default=False, verbose_name='Хорошо продаваема?'),
        ),
    ]
